// This file is only used by pull.js to generate files. It is not used at runtime.

const addons = [
    'cat-blocks',
    'editor-devtools',
    'editor-searchable-dropdowns',
    'data-category-tweaks-v2',
    'block-palette-icons',
    'hide-flyout',
    'mediarecorder',
    'drag-drop',
    'debugger',
    'pause',
    'mute-project',
    'clones',
    'mouse-pos',
    'color-picker',
    'remove-sprite-confirm',
    'block-count',
    'onion-skinning',
    'default-costume-editor-color',
    'bitmap-copy',
    '2d-color-picker',
    'better-img-uploads',
    'pick-colors-from-stage',
    'custom-block-shape',
    'zebra-striping',
    'editor-theme3',
    'custom-block-text',
    'editor-colored-context-menus',
    'editor-stage-left',
    'editor-buttons-reverse-order',
    'variable-manager',
    'search-sprites',
    'gamepad',
    'editor-sounds',
    'folders',
    'block-switching',
    'load-extensions',
    'custom-zoom',
    'initialise-sprite-position',
    'blocks2image',
    'remove-curved-stage-border',
    'transparent-orphans',
    'paint-by-default',
    'block-cherry-picking',
    'hide-new-variables',
    'editor-extra-keys',
    'hide-delete-button',
    'no-script-bumping',
    'disable-stage-drag-select',
    'move-to-top-bottom',
    'disable-paste-offset',
    'block-duplicate',
    'swap-local-global',
    'editor-comment-previews',
    'columns',
    'script-snap',
    'fullscreen',
    'hide-stage',
    'tw-straighten-comments',
    'tw-remove-backpack',
    'tw-remove-feedback',
    'tw-disable-compiler',
    'editor-stepping'
];

const newAddons = [
    'pick-colors-from-stage',
    'zebra-striping'
];

// eslint-disable-next-line import/no-commonjs
module.exports = {
    addons,
    newAddons
};
