/* generated by pull.js */
import _js from "./remove-backpack.js";
import _css from "!css-loader!./remove-backpack.css";
export const resources = {
  "remove-backpack.js": _js,
  "remove-backpack.css": _css,
};
