/* generated by pull.js */
import _css from "!css-loader!./text-bold.css";
import _css2 from "!css-loader!./text-shadow.css";
export const resources = {
  "text-bold.css": _css,
  "text-shadow.css": _css2,
};
