/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _css2 from "!css-loader!./gamepadlib.css";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "gamepadlib.css": _css2,
};
