/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./hideOverflow.css";
import _css2 from "!css-loader!./removeBorder.css";
import _css3 from "!css-loader!./resizeWindow.css";
import _css4 from "!css-loader!./resizeWindow_noToolbar.css";
import _css5 from "!css-loader!./hideToolbar.css";
export const resources = {
  "userscript.js": _js,
  "hideOverflow.css": _css,
  "removeBorder.css": _css2,
  "resizeWindow.css": _css3,
  "resizeWindow_noToolbar.css": _css4,
  "hideToolbar.css": _css5,
};
